swagger: "2.0"
info:
  title: Collection Service
  version: 0.0.1
tags:
  - name: CollectionService
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/bases/{base_id}/collections:
    post:
      operationId: CreateCollection
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/collectionCreateCollectionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: base_id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CollectionServiceCreateCollectionBody'
      tags:
        - CollectionService
  /api/v1/bases/{base_id}/collections/{collection_id}:
    get:
      operationId: GetCollectionById
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/collectionGetCollectionByIdResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: base_id
          in: path
          required: true
          type: string
        - name: collection_id
          in: path
          required: true
          type: string
      tags:
        - CollectionService
    delete:
      operationId: DeleteCollectionById
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/collectionDeleteCollectionByIdResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: base_id
          in: path
          required: true
          type: string
        - name: collection_id
          in: path
          required: true
          type: string
      tags:
        - CollectionService
definitions:
  CollectionServiceCreateCollectionBody:
    type: object
    properties:
      owner_id:
        type: string
      topic:
        type: string
      description:
        type: string
  collectionCreateCollectionResponse:
    type: object
    properties:
      collection:
        $ref: '#/definitions/commonCollection'
  collectionDeleteCollectionByIdResponse:
    type: object
  collectionGetCollectionByIdResponse:
    type: object
    properties:
      collection:
        $ref: '#/definitions/commonCollection'
  commonCollection:
    type: object
    properties:
      id:
        type: string
      base_id:
        type: string
      owner_id:
        type: string
      topic:
        type: string
      description:
        type: string
      page_ids:
        type: array
        items:
          type: string
      created_at:
        type: string
        format: date-time
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
