version: '3.8'

services:
  note_app:
    build:
      context: ./note
  user_app:
    build:
      context: ./user
  database:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    restart: on-failure
  swagger:
    environment:
      URLS: >
        [ 
          { url: "http://localhost:8044/api/v1/note.openapi.yaml", name: "Note API" },
          { url: "http://localhost:8034/api/v1/user.openapi.yaml", name: "User API" },
          { url: "http://localhost:8034/api/v1/auth.openapi.yaml", name: "Auth API" }
        ]
