version: '3.8'

services:
  note_app:
    build:
      context: ./note
  user_app:
    build:
      context: ./user
  database:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    restart: on-failure
  swagger:
    environment:
      URLS: >
        [ 
          { url: "http://localhost:8014/api/note/v1/note.openapi.yaml", name: "Note API" },
          { url: "http://localhost:8014/api/user/v1/user.openapi.yaml", name: "User API" },
          { url: "http://localhost:8014/api/user/v1/auth.openapi.yaml", name: "Auth API" }
        ]
  nginx:
    image: nginx:1.27.0
    volumes:
      - './deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './deploy/nginx/conf.d:/etc/nginx/conf.d:ro'
