swagger: "2.0"
info:
  title: Topic Service
  version: 0.0.1
tags:
  - name: TopicService
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/knowledge-bases/{knowledge_base_id}/collections/{collection_id}/topics:
    get:
      operationId: TopicService_GetByCollection
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/topicGetByCollectionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: knowledge_base_id
          in: path
          required: true
          type: string
        - name: collection_id
          in: path
          required: true
          type: string
      tags:
        - TopicService
    post:
      operationId: CreateTopic
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/topicCreateTopicResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: knowledge_base_id
          in: path
          required: true
          type: string
        - name: collection_id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TopicServiceCreateTopicBody'
      tags:
        - TopicService
  /api/v1/knowledge-bases/{knowledge_base_id}/collections/{collection_id}/topics/{topic_id}:
    get:
      operationId: GetTopicById
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/topicGetTopicByIdResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: knowledge_base_id
          in: path
          required: true
          type: string
        - name: collection_id
          in: path
          required: true
          type: string
        - name: topic_id
          in: path
          required: true
          type: string
      tags:
        - TopicService
    delete:
      operationId: DeleteTopicById
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/topicDeleteTopicByIdResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: knowledge_base_id
          in: path
          required: true
          type: string
        - name: collection_id
          in: path
          required: true
          type: string
        - name: topic_id
          in: path
          required: true
          type: string
      tags:
        - TopicService
definitions:
  TopicServiceCreateTopicBody:
    type: object
    properties:
      owner_id:
        type: string
      topic:
        type: string
      description:
        type: string
  commonTopic:
    type: object
    properties:
      id:
        type: string
      knowledge_base_id:
        type: string
      collection_id:
        type: string
      owner_id:
        type: string
      topic:
        type: string
      description:
        type: string
      order:
        type: integer
        format: int32
      created_at:
        type: string
        format: date-time
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  topicCreateTopicResponse:
    type: object
    properties:
      topic:
        $ref: '#/definitions/commonTopic'
  topicDeleteTopicByIdResponse:
    type: object
  topicGetByCollectionResponse:
    type: object
    properties:
      topics:
        type: array
        items:
          type: object
          $ref: '#/definitions/commonTopic'
  topicGetTopicByIdResponse:
    type: object
    properties:
      topic:
        $ref: '#/definitions/commonTopic'
