version: '3.8'

networks:
  user:

services:
  app:
    container_name: app
    build:
      dockerfile: ../build/Dockerfile
    restart: on-failure
    networks:
      - user
    environment:
      - DATABASE_URL="host=db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - '8001:1028'
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    networks:
      - user
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    
