version: '3.8'

networks:
  reverse_proxy_user:
  swagger:
  database:

volumes:
  database_data:

services:
  user_app:
    build:
      dockerfile: ../build/Dockerfile
    restart: on-failure
    networks:
      - reverse_proxy_user
      - database
    depends_on:
      - database
    command:
      - '-db-username=database_user'
      - '-db-password=database_user_password'
      - '-db-address=database:27017'
  database:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    restart: on-failure
    networks:
      - database
    ports:
      - '27017:27017'
    volumes:
      - 'database_data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: database_user
      MONGO_INITDB_ROOT_PASSWORD: database_user_password
  swagger:
    image: swaggerapi/swagger-ui:v5.17.7
    restart: on-failure
    networks:
      - swagger
    environment:
      PORT: 80
      URLS: >
        [ 
          { url: "http://localhost:8014/api/user/v1/user.openapi.yaml", name: "User API" },
          { url: "http://localhost:8014/api/user/v1/auth.openapi.yaml", name: "Auth API" }
        ]
  nginx:
    image: nginx:1.27.0
    restart: on-failure
    networks:
      - swagger
      - reverse_proxy_user
    ports:
      - '8010:80'
      - '8014:84'
    volumes:
      - '../deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '../deploy/nginx/conf.d:/etc/nginx/conf.d:ro'
    depends_on:
      - user_app
      - swagger
