openapi: 3.0.3
info:
  title: Note API
  description: This API provides an interface for creating and managing notes.
  version: 1.0.0
servers:
  - url: http://localhost:8040/api/v1
    description: Server for local development
paths:
  /{workspace}/notes:
    get:
      description: This endpoint returns the user's notes.
      operationId: ListNotes
      tags:
        - notes
      parameters:
        - $ref: '#/components/parameters/Workspace'
      responses:
        '200':
          $ref: '#/components/responses/ListNotesResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
    post:
      description: This endpoint creates a user's note.
      operationId: CreateNote
      tags:
        - notes
      parameters:
        - $ref: '#/components/parameters/Workspace'
      requestBody:
        $ref: '#/components/requestBodies/CreateNoteRequest'
      responses:
        '201':
          $ref: '#/components/responses/CreateNoteResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
components:
  parameters:
    Workspace:
      description: This parameter defines the current workspace.
      in: path
      name: workspace
      schema:
        type: string
      required: true

  schemas:
    Note:
      type: object
      required:
        - id
        - title
        - workspace
      properties:
        id:
          type: string
          nullable: false
        title:
          type: string
          nullable: false
        workspace:
          type: string
          nullable: false

  requestBodies:
    CreateNoteRequest:
      content:
        'application/json':
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
                nullable: false

  responses:
    DefaultErrorResponse:
      description: Default response model for response codes 4** and 5**.
      content:
        'application/json':
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: string
                nullable: false
              message:
                type: string
                nullable: false

    ListNotesResponse:
      description: List of user notes.
      content:
        'application/json':
          schema:
            type: object
            required:
              - notes
            properties:
              notes:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
                nullable: false

    CreateNoteResponse:
      description: The note has been successfully created.
      content:
        'application/json':
          schema:
            type: object
            required:
              - id
            properties:
              id:
                type: string
                nullable: false
