openapi: 3.0.3
info:
  title: Note API
  description: This API provides an interface for creating and managing notes.
  version: 1.0.0
servers:
  - url: http://localhost:8010/api/note/v1
    description: Server for local development.
paths:
  /{workspace}/notes:
    get:
      description: This endpoint returns the user's notes.
      operationId: ListNotes
      tags:
        - notes
      parameters:
        - $ref: '#/components/parameters/Workspace'
      responses:
        '200':
          $ref: '#/components/responses/ListNotesResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
    post:
      description: This endpoint creates a user's note.
      operationId: CreateNote
      tags:
        - notes
      parameters:
        - $ref: '#/components/parameters/Workspace'
      requestBody:
        $ref: '#/components/requestBodies/CreateNoteRequest'
      responses:
        '201':
          $ref: '#/components/responses/CreateNoteResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'

  /{workspace}/notes/{note-id}:
    patch:
      description: This endpoint updates the user's note. The body must contain note metadata and note file.
      operationId: UpdateNote
      tags:
        - notes
      parameters:
        - $ref: '#/components/parameters/Workspace'
        - $ref: '#/components/parameters/NoteId'
      requestBody:
        $ref: '#/components/requestBodies/UpdateNoteRequest'
      responses:
        '201':
          $ref: '#/components/responses/UpdateNoteResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'

components:
  parameters:
    Workspace:
      description: This parameter defines the current workspace.
      in: path
      name: workspace
      schema:
        type: string
      required: true

    NoteId:
      description: This parameter defines the current note id.
      in: path
      name: note-id
      schema:
        type: string
      required: true

  schemas:
    Note:
      type: object
      required:
        - id
        - title
        - workspace
        - content_uri
      properties:
        id:
          type: string
          nullable: false
        title:
          type: string
          nullable: true
        workspace:
          type: string
          nullable: false
        content_uri:
          type: string
          nullable: false

    UpdateNotePart:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          nullable: true

  requestBodies:
    CreateNoteRequest:
      content:
        'application/json':
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
                nullable: true

    UpdateNoteRequest:
      content:
        'multipart/form-data':
          schema:
            type: object
            required:
              - note
            properties:
              note:
                $ref: '#/components/schemas/UpdateNotePart'
              file:
                type: string
                format: binary

  responses:
    DefaultErrorResponse:
      description: Default response model for response codes 4** and 5**.
      content:
        'application/json':
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: string
                nullable: false
              message:
                type: string
                nullable: false

    ListNotesResponse:
      description: List of user notes.
      content:
        'application/json':
          schema:
            type: object
            required:
              - notes
            properties:
              notes:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
                nullable: false

    CreateNoteResponse:
      description: The note has been successfully created.
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Note'

    UpdateNoteResponse:
      description: The note has been successfully updated.
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Note'
